services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: global_messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - messenger_pg:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "2525:1025"
      - "8025:8025"

volumes:
  messenger_pg:
