import { io, Socket } from 'socket.io-client';
import { startRingtone, stopRingtone } from './sounds';
const API=import.meta.env.VITE_API_URL??'http://localhost:4000';const PREFIX='__GM_CALL__';let socket:Socket|null=null,pc:RTCPeerConnection|null=null,stream:MediaStream|null=null,callId='',callConversation='',callKind:'audio'|'video'='audio';let overlay:HTMLDivElement|null=null;let timer:number|undefined;let seconds=0;let muted=false,cameraOff=false;
const esc=(s:string)=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]!));
function ui(html:string){if(!overlay){overlay=document.createElement('div');overlay.id='gm-feature-overlay';Object.assign(overlay.style,{position:'fixed',inset:'0',zIndex:'99999',display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(2,6,23,.9)',fontFamily:'system-ui'});document.body.appendChild(overlay)}overlay.innerHTML=html;overlay.style.display='flex';return overlay}
function close(){if(overlay)overlay.style.display='none'}
function formatTime(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');return `${m}:${s}`}
function startTimer(){seconds=0;if(timer)clearInterval(timer);timer=window.setInterval(()=>{seconds++;const el=document.getElementById('gm-timer');if(el)el.textContent=formatTime()},1000)}
function stopTimer(){if(timer)clearInterval(timer);timer=undefined}
function localPreview(){const v=document.getElementById('gm-local') as HTMLVideoElement|null;if(v&&stream)v.srcObject=stream}
function renderCall(title:string,showLocal:boolean){ui(`<div style="position:relative;background:#0f172a;color:#fff;width:min(96vw,900px);height:min(88vh,700px);border-radius:24px;overflow:hidden;box-shadow:0 25px 80px #000"><div style="position:absolute;z-index:2;top:0;left:0;right:0;padding:18px 22px;background:linear-gradient(#0009,transparent);display:flex;justify-content:space-between"><div><b>${title}</b><div id="gm-timer" style="font-size:13px;color:#cbd5e1">00:00</div></div><span>${callKind==='video'?'📹':'📞'}</span></div><video id="gm-remote" autoplay playsinline style="width:100%;height:100%;object-fit:cover;background:#020617"></video>${showLocal&&callKind==='video'?'<video id="gm-local" autoplay muted playsinline style="position:absolute;right:18px;top:70px;width:180px;height:125px;object-fit:cover;background:#111827;border:2px solid #fff5;border-radius:14px"></video>':''}<div style="position:absolute;bottom:0;left:0;right:0;padding:22px;display:flex;justify-content:center;gap:12px;background:linear-gradient(transparent,#000b)"><button id="gm-mute" style="border:0;border-radius:50%;width:52px;height:52px;font-size:20px">🎙️</button>${callKind==='video'?'<button id="gm-camera" style="border:0;border-radius:50%;width:52px;height:52px;font-size:20px">📷</button>':''}<button id="gm-end" style="border:0;border-radius:50%;width:58px;height:58px;background:#ef4444;color:#fff;font-size:22px">📵</button></div></div>`);document.getElementById('gm-end')!.onclick=()=>end(true);document.getElementById('gm-mute')!.onclick=()=>toggleMute();document.getElementById('gm-camera')?.addEventListener('click',toggleCamera);localPreview();startTimer()}
async function conversations(){const token=localStorage.getItem('gm_token');if(!token)return[];const r=await fetch(`${API}/api/conversations`,{headers:{Authorization:`Bearer ${token}`}});return r.ok?r.json():[]}
async function activeConversation(){const title=(document.querySelector('.chat-heading b')?.textContent||'').trim();if(!title)return null;const me=JSON.parse(localStorage.getItem('gm_user')||'{}');const cs=await conversations();return cs.find((c:any)=>c.isGroup?(c.title||'Group')===title:c.members?.some((m:any)=>m.user.id!==me.id&&m.user.displayName===title))||null}
function sendSignal(conversationId:string,data:any){socket?.emit('message:send',{conversationId,body:`${PREFIX}${JSON.stringify(data)}`,type:'call-signal',clientId:crypto.randomUUID()})}
function sendCallLog(conversationId:string,kind:'audio'|'video',status:'missed'|'declined'|'completed'){socket?.emit('message:send',{conversationId,body:`${kind==='video'?'📹 Video':'📞 Voice'} call · ${status}`,type:'call-log',clientId:crypto.randomUUID()})}
function hideSignalMessages(){document.querySelectorAll('.bubble').forEach(b=>{if((b.textContent||'').includes(PREFIX))b.parentElement?.remove()})}
function permissionHelp(kind:'audio'|'video'){const needs=kind==='video'?'camera and microphone':'microphone';ui(`<div style="background:#111827;color:#fff;padding:30px;border-radius:22px;width:min(92vw,470px);text-align:center"><div style="font-size:52px">🔐</div><h2>Allow ${needs}</h2><p style="line-height:1.65;color:#cbd5e1">Click <b>Allow</b> when your browser asks. If there is no prompt, click the <b>🔒 site icon beside the address bar</b>, set <b>Camera</b> and <b>Microphone</b> to <b>Allow</b>, reload Messenger, and try again.</p><button id="gm-permission" style="padding:12px 24px;border:0;border-radius:999px;background:#22c55e;color:#fff;font-weight:700">Try again</button><button id="gm-perm-close" style="padding:12px 24px;margin-left:8px;border:0;border-radius:999px">Cancel</button></div>`);document.getElementById('gm-permission')!.onclick=()=>{close();setTimeout(()=>requestMedia(kind),0)};document.getElementById('gm-perm-close')!.onclick=()=>{stopRingtone();close()}}
async function requestMedia(kind:'audio'|'video'){try{return await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'})}catch{permissionHelp(kind);return null}}
function ensureSocket(){if(socket?.connected)return socket;const token=localStorage.getItem('gm_token');if(!token)return null;socket=io(API,{auth:{token},transports:['websocket','polling'],reconnection:true,reconnectionAttempts:Infinity});socket.on('message:new',(m:any)=>{if(typeof m.body!=='string'||!m.body.startsWith(PREFIX))return;hideSignalMessages();try{const d=JSON.parse(m.body.slice(PREFIX.length));if(d.kind==='offer')incoming(m.conversationId,d);else if(d.kind==='answer'&&d.callId===callId)answer(d);else if(d.kind==='ice'&&d.callId===callId)ice(d);else if(d.kind==='reject'&&d.callId===callId){stopRingtone();sendCallLog(callConversation,callKind,'declined');end(false)}else if(d.kind==='end'&&d.callId===callId){sendCallLog(callConversation,callKind,'completed');end(false)}}catch{}});return socket}
async function call(kind:'audio'|'video'){stopRingtone();const s=ensureSocket(),c=await activeConversation();if(!s?.connected)return alert('Realtime connection is not ready. Please wait a moment.');if(!c)return alert('Open the conversation before starting a call.');callId=crypto.randomUUID();callConversation=c.id;callKind=kind;muted=false;cameraOff=false;stream=await requestMedia(kind);if(!stream){callId='';return}pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc!.addTrack(t,stream!));pc.onicecandidate=e=>e.candidate&&sendSignal(c.id,{kind:'ice',callId,candidate:e.candidate});pc.ontrack=e=>{const v=document.getElementById('gm-remote') as HTMLVideoElement|null;if(v)v.srcObject=e.streams[0]};const offer=await pc.createOffer();await pc.setLocalDescription(offer);sendSignal(c.id,{kind:'offer',callId,callKind:kind,offer,fromName:JSON.parse(localStorage.getItem('gm_user')||'{}').displayName});renderCall(`Calling ${chatLabel()}`,kind==='video');hideSignalMessages()}
function chatLabel(){return (document.querySelector('.chat-heading b')?.textContent||'Contact').trim()}
async function incoming(conversationId:string,d:any){if(callId)return;callId=d.callId;callConversation=conversationId;callKind=d.callKind==='video'?'video':'audio';startRingtone(callKind==='video');ui(`<div style="background:#111827;color:#fff;padding:32px;border-radius:24px;width:min(90vw,420px);text-align:center"><div style="font-size:56px">${callKind==='video'?'📹':'📞'}</div><h2>Incoming ${callKind==='video'?'video':'voice'} call</h2><p>${esc(d.fromName||'Contact')} is calling</p><button id="gm-no" style="padding:12px 22px;margin:8px;border:0;border-radius:999px;background:#ef4444;color:#fff">Decline</button><button id="gm-yes" style="padding:12px 22px;margin:8px;border:0;border-radius:999px;background:#22c55e;color:#fff">Accept</button></div>`);document.getElementById('gm-no')!.onclick=()=>{stopRingtone();sendSignal(conversationId,{kind:'reject',callId:d.callId});sendCallLog(conversationId,callKind,'declined');callId='';close()};document.getElementById('gm-yes')!.onclick=()=>{stopRingtone();accept(d)}}
async function accept(d:any){stream=await requestMedia(d.callKind==='video'?'video':'audio');if(!stream)return;muted=false;cameraOff=false;pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc!.addTrack(t,stream!));pc.onicecandidate=e=>e.candidate&&sendSignal(callConversation,{kind:'ice',callId:d.callId,candidate:e.candidate});pc.ontrack=e=>{const v=document.getElementById('gm-remote') as HTMLVideoElement|null;if(v)v.srcObject=e.streams[0]};await pc.setRemoteDescription(d.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);sendSignal(callConversation,{kind:'answer',callId:d.callId,answer});renderCall(`Connected with ${esc(d.fromName||'Contact')}`,d.callKind==='video');hideSignalMessages()}
function toggleMute(){muted=!muted;stream?.getAudioTracks().forEach(t=>t.enabled=!muted);const b=document.getElementById('gm-mute');if(b)b.textContent=muted?'🔇':'🎙️'}
function toggleCamera(){cameraOff=!cameraOff;stream?.getVideoTracks().forEach(t=>t.enabled=!cameraOff);const b=document.getElementById('gm-camera');if(b)b.textContent=cameraOff?'🚫':'📷'}
async function answer(d:any){if(pc)await pc.setRemoteDescription(d.answer)}async function ice(d:any){if(pc&&d.candidate)try{await pc.addIceCandidate(d.candidate)}catch{}}
function end(notify:boolean){stopRingtone();stopTimer();if(notify&&callConversation){sendSignal(callConversation,{kind:'end',callId});sendCallLog(callConversation,callKind,'completed')}stream?.getTracks().forEach(t=>t.stop());pc?.close();stream=null;pc=null;callId='';callConversation='';close();hideSignalMessages()}
function features(){ui(`<div style="background:#111827;color:#fff;padding:28px;border-radius:22px;width:min(90vw,500px)"><h2>✨ Explore features</h2><p>Global Messenger tools</p><button id="gm-v" style="display:block;width:100%;padding:14px;margin:8px 0">📹 Video call</button><button id="gm-a" style="display:block;width:100%;padding:14px;margin:8px 0">📞 Voice call</button><button id="gm-f" style="display:block;width:100%;padding:14px;margin:8px 0">📎 File sharing</button><button id="gm-c" style="display:block;width:100%;padding:12px;margin-top:12px">Close</button></div>`);document.getElementById('gm-v')!.onclick=()=>call('video');document.getElementById('gm-a')!.onclick=()=>call('audio');document.getElementById('gm-f')!.onclick=()=>{close();document.querySelector<HTMLInputElement>('input[type=file]')?.click()};document.getElementById('gm-c')!.onclick=close}
function options(){ui(`<div style="background:#111827;color:#fff;padding:24px;border-radius:18px;width:min(90vw,380px)"><h3>Conversation options</h3><button id="gm-info" style="display:block;width:100%;padding:12px;margin:7px 0">👤 Contact info</button><button id="gm-copy" style="display:block;width:100%;padding:12px;margin:7px 0">🔗 Copy messenger link</button><button id="gm-close" style="display:block;width:100%;padding:12px;margin:7px 0">Close</button></div>`);document.getElementById('gm-info')!.onclick=()=>alert('Conversation options are available here.');document.getElementById('gm-copy')!.onclick=async()=>{try{await navigator.clipboard.writeText(location.href);alert('Link copied')}catch{alert('Unable to copy link')}};document.getElementById('gm-close')!.onclick=close}
document.addEventListener('click',e=>{const t=e.target as HTMLElement;if(t.closest('.top-actions .icon-btn:nth-child(1)'))call('audio');else if(t.closest('.top-actions .icon-btn:nth-child(2)'))call('video');else if(t.closest('.top-actions .icon-btn:nth-child(3)'))options();else if(t.closest('.sidebar-bottom button'))features()});setTimeout(ensureSocket,700);setInterval(hideSignalMessages,1000);