name = "global-messenger-api"
main = "src/index.ts"
compatibility_date = "2026-08-31"

[vars]
UPSTREAM_API = "https://global-messenger-api.onrender.com"
ALLOWED_ORIGIN = "https://global-messenger-web.narsingbeesetti006.workers.dev"
